### ISSUE TITLE
Failed to connect to argilla, Unexpected response: Cannot parse json data from response

### ISSUE THREAD

**Issue by yizhennn** [Eladlev/AutoPrompt#101]
I'm using Argilla as an annotator with the deploy space on Hugging Face. However, while running pipeline.py, I encountered an error stating that the request results cannot be parsed.

Could you please help me troubleshoot this? I'd really appreciate any guidance—I'm feeling a bit stuck. Thank you so much!

Error: 

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\_helpers.py:48   │
│ in check_response                                                                                │
│                                                                                                  │
│   45 def check_response(response: httpx.Response, **kwargs) -> Any:                              │
│   46 │   if 200 <= response.status_code < 300:                                                   │
│   47 │   │   try:                                                                                │
│ ❱ 48 │   │   │   return response.json()                                                          │
│   49 │   │   except JSONDecodeError:                                                             │
│   50 │   │   │   raise WrongResponseError(                                                       │
│   51 │   │   │   │   message="Cannot parse json data from response",                             │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\httpx\_models.py:762 in json        │
│                                                                                                  │
│    759 │   │   raise HTTPStatusError(message, request=request, response=self)                    │
│    760 │                                                                                         │
│    761 │   def json(self, **kwargs: typing.Any) -> typing.Any:                                   │
│ ❱  762 │   │   return jsonlib.loads(self.content, **kwargs)                                      │
│    763 │                                                                                         │
│    764 │   @property                                                                             │
│    765 │   def cookies(self) -> "Cookies":                                                       │
│                                                                                                  │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py:346 in loads          │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ ❱ 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py:337 in decode          │
│                                                                                                  │
│   334 │   │   containing a JSON document).                                                       │
│   335 │   │                                                                                      │
│   336 │   │   """                                                                                │
│ ❱ 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│   340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│                                                                                                  │
│ C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py:355 in raw_decode      │
│                                                                                                  │
│   352 │   │   try:                                                                               │
│   353 │   │   │   obj, end = self.scan_once(s, idx)                                              │
│   354 │   │   except StopIteration as err:                                                       │
│ ❱ 355 │   │   │   raise JSONDecodeError("Expecting value", s, err.value) from None               │
│   356 │   │   return obj, end                                                                    │
│   357                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ c:\Users\USER\Desktop\autop\AutoPrompt\estimator\estimator_argilla.py:22 in __init__             │
│                                                                                                  │
│    19 │   │   """                                                                                │
│    20 │   │   try:                                                                               │
│    21 │   │   │   self.opt = opt                                                                 │
│ ❱  22 │   │   │   rg.init(                                                                       │
│    23 │   │   │   │   api_url=opt.api_url,                                                       │
│    24 │   │   │   │   api_key=opt.api_key,                                                       │
│    25 │   │   │   │   workspace=opt.workspace                                                    │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\singleton.py:95 in   │
│ init                                                                                             │
│                                                                                                  │
│    92 │   │   >>> headers = {"X-Client-id":"id","X-Secret":"secret"}                             │
│    93 │   │   >>> rg.init(api_url="http://localhost:9090", api_key="4AkeAPIk3Y", extra_headers   │
│    94 │   """                                                                                    │
│ ❱  95 │   ArgillaSingleton.init(                                                                 │
│    96 │   │   api_url=api_url,                                                                   │
│    97 │   │   api_key=api_key,                                                                   │
│    98 │   │   workspace=workspace,                                                               │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\singleton.py:47 in   │
│ init                                                                                             │
│                                                                                                  │
│    44 │   ) -> Argilla:                                                                          │
│    45 │   │   cls._INSTANCE = None                                                               │
│    46 │   │                                                                                      │
│ ❱  47 │   │   cls._INSTANCE = Argilla(                                                           │
│    48 │   │   │   api_url=api_url,                                                               │
│    49 │   │   │   api_key=api_key,                                                               │
│    50 │   │   │   timeout=timeout,                                                               │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\client.py:164 in     │
│ __init__                                                                                         │
│                                                                                                  │
│   161 │   │   │   httpx_extra_kwargs=httpx_extra_kwargs,                                         │
│   162 │   │   )                                                                                  │
│   163 │   │                                                                                      │
│ ❱ 164 │   │   self._user = users_api.whoami(client=self.http_client)  # .parsed                  │
│   165 │   │                                                                                      │
│   166 │   │   if not workspace and self._user.username == DEFAULT_USERNAME and DEFAULT_USERNAM   │
│   167 │   │   │   warnings.warn(                                                                 │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\users\api.py:39  │
│ in whoami                                                                                        │
│                                                                                                  │
│    36 │   """                                                                                    │
│    37 │   url = "/api/me"                                                                        │
│    38 │                                                                                          │
│ ❱  39 │   response = client.get(url)                                                             │
│    40 │   return UserModel(**response)                                                           │
│    41                                                                                            │
│    42                                                                                            │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\client.py:124 in │
│ inner                                                                                            │
│                                                                                                  │
│   121 │   │   @functools.wraps(func)                                                             │
│   122 │   │   def inner(self, *args, **kwargs):                                                  │
│   123 │   │   │   try:                                                                           │
│ ❱ 124 │   │   │   │   result = func(self, *args, **kwargs)                                       │
│   125 │   │   │   │   return result                                                              │
│   126 │   │   │   except httpx.ConnectError as err:                                              │
│   127 │   │   │   │   err_str = f"Your Api endpoint at {self.base_url} is not available or not   │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\client.py:141 in │
│ get                                                                                              │
│                                                                                                  │
│   138 │   │   │   *args,                                                                         │
│   139 │   │   │   **kwargs,                                                                      │
│   140 │   │   )                                                                                  │
│ ❱ 141 │   │   return build_raw_response(response).parsed                                         │
│   142 │                                                                                          │
│   143 │   @with_httpx_error_handler                                                              │
│   144 │   def patch(self, path: str, *args, **kwargs):                                           │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\_helpers.py:25   │
│ in build_raw_response                                                                            │
│                                                                                                  │
│   22                                                                                             │
│   23                                                                                             │
│   24 def build_raw_response(response: httpx.Response) -> Response[Union[Dict[str, Any], Error    │
│ ❱ 25 │   return build_typed_response(response)                                                   │
│   26                                                                                             │
│   27                                                                                             │
│   28 ResponseType = TypeVar("ResponseType")                                                      │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\_helpers.py:34   │
│ in build_typed_response                                                                          │
│                                                                                                  │
│   31 def build_typed_response(                                                                   │
│   32 │   response: httpx.Response, response_type_class: Optional[Type[ResponseType]] = None      │
│   33 ) -> Response[Union[ResponseType, ErrorMessage, HTTPValidationError]]:                      │
│ ❱ 34 │   parsed_response = check_response(response, expected_response=response_type_class)       │
│   35 │   if response_type_class:                                                                 │
│   36 │   │   parsed_response = response_type_class(**parsed_response)                            │
│   37 │   return Response(                                                                        │
│                                                                                                  │
│ C:\Users\USER\Desktop\autop\AutoPrompt\env\lib\site-packages\argilla\client\sdk\_helpers.py:50   │
│ in check_response                                                                                │
│                                                                                                  │
│   47 │   │   try:                                                                                │
│   48 │   │   │   return response.json()                                                          │
│   49 │   │   except JSONDecodeError:                                                             │
│ ❱ 50 │   │   │   raise WrongResponseError(                                                       │
│   51 │   │   │   │   message="Cannot parse json data from response",                             │
│   52 │   │   │   │   response=response.content,                                                  │
│   53 │   │   │   )                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
WrongResponseError: 
Unexpected response: Cannot parse json data from response
Response content:
b'<!doctype html>\n<html>\n  <head>\n    <meta data-n-head="1" charset="utf-8"><meta data-n-head="1" name="viewport" content="width=device-width,initial-scale=1"><meta data-n-head="1" data-hid="description"   
name="description" content=""><title>Argilla</title><link data-n-head="1" rel="icon" type="image/x-icon" href="favicon.ico"><link data-n-head="1" rel="apple-touch-icon" sizes="180x180"
href="apple-touch-icon.png"><link data-n-head="1" rel="icon" sizes="32x32" href="favicon-32x32.png"><link data-n-head="1" rel="icon" sizes="16x16" href="favicon-16x16.png"><link data-n-head="1" rel="manifest" 
href="site.webmanifest"><base href="/"><link rel="preload" href="/_nuxt/5866dd8.js" as="script"><link rel="preload" href="/_nuxt/dcd7bdf.js" as="script"><link rel="preload" href="/_nuxt/9feeefc.js"
as="script"><link rel="preload" href="/_nuxt/e9267f8.js" as="script">\n  </head>\n  <body>\n    <div
id="__nuxt"><style>#nuxt-loading{background:#fff;visibility:hidden;opacity:0;position:absolute;left:0;right:0;top:0;bottom:0;display:flex;justify-content:center;align-items:center;flex-direction:column;animati
on:nuxtLoadingIn 10s ease;-webkit-animation:nuxtLoadingIn 10s ease;animation-fill-mode:forwards;overflow:hidden}@keyframes
nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}@-webkit-keyframes
nuxtLoadingIn{0%{visibility:hidden;opacity:0}20%{visibility:visible;opacity:0}100%{visibility:visible;opacity:1}}#nuxt-loading>div,#nuxt-loading>div:after{border-radius:50%;width:5rem;height:5rem}#nuxt-loading
>div{font-size:10px;position:relative;text-indent:-9999em;border:.5rem solid #f5f5f5;border-left:.5rem solid
#d3d3d3;-webkit-transform:translateZ(0);-ms-transform:translateZ(0);transform:translateZ(0);-webkit-animation:nuxtLoading 1.1s infinite linear;animation:nuxtLoading 1.1s infinite
linear}#nuxt-loading.error>div{border-left:.5rem solid #ff4500;animation-duration:5s}@-webkit-keyframes
nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}@keyframes
nuxtLoading{0%{-webkit-transform:rotate(0);transform:rotate(0)}100%{-webkit-transform:rotate(360deg);transform:rotate(360deg)}}</style> <script>window.addEventListener("error",(function(){var
e=document.getElementById("nuxt-loading");e&&(e.className+=" error")}))</script> <div id="nuxt-loading" aria-live="polite" role="status"><div>Loading...</div></div>
</div><script>window.__NUXT__={config:{clientVersion:"2.4.0",documentationSite:"https://docs.argilla.io/",documentationPersistentStorage:"https://docs.argilla.io/latest/getting_started/how-to-configure-argilla
-on-huggingface/#persistent-storage",_app:{basePath:"/",assetsPath:"/_nuxt/",cdnURL:null}}}</script>\n  <script src="/_nuxt/5866dd8.js"></script><script src="/_nuxt/dcd7bdf.js"></script><script
src="/_nuxt/9feeefc.js"></script><script src="/_nuxt/e9267f8.js"></script></body>\n</html>\n'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ c:\Users\USER\Desktop\autop\AutoPrompt\run_pipeline.py:41 in <module>                            │
│                                                                                                  │
│   38 │   initial_prompt = opt.prompt                                                             │
│   39                                                                                             │
│   40 # Initializing the pipeline                                                                 │
│ ❱ 41 pipeline = OptimizationPipeline(config_params, task_description, initial_prompt, output_    │
│   42 if (opt.load_path != ''):                                                                   │
│   43 │   pipeline.load_state(opt.load_path)                                                      │
│   44 best_prompt = pipeline.run_pipeline(opt.num_steps)                                          │
│                                                                                                  │
│ c:\Users\USER\Desktop\autop\AutoPrompt\optimization_pipeline.py:57 in __init__                   │
│                                                                                                  │
│    54 │   │   self.cur_prompt = initial_prompt                                                   │
│    55 │   │                                                                                      │
│    56 │   │   self.predictor = give_estimator(config.predictor)                                  │
│ ❱  57 │   │   self.annotator = give_estimator(config.annotator)                                  │
│    58 │   │   self.eval = Eval(config.eval, self.meta_chain.error_analysis, self.dataset.label   │
│    59 │   │   self.batch_id = 0                                                                  │
│    59 │   │   self.batch_id = 0                                                                  │
│    59 │   │   self.batch_id = 0                                                                  │
│    60 │   │   self.patient = 0                                                                   │
│                                                                                                  │
│    59 │   │   self.batch_id = 0                                                                  │
│    60 │   │   self.patient = 0                                                                   │
│                                                                                                  │
│ c:\Users\USER\Desktop\autop\AutoPrompt\estimator\__init__.py:31 in give_estimator                │
│                                                                                                  │
│   28                                                                                             │
│   29 def give_estimator(opt):                                                                    │
│   30 │   if opt.method == 'argilla':                                                             │
│ ❱ 31 │   │   return ArgillaEstimator(opt.config)                                                 │
│   32 │   elif opt.method == 'llm':                                                               │
│   33 │   │   return LLMEstimator(opt.config)                                                     │
│   34 │   elif opt.method == 'llm_batch':                                                         │
│                                                                                                  │
│    59 │   │   self.batch_id = 0                                                                  │
│    60 │   │   self.patient = 0                                                                   │
│                                                                                                  │
│ c:\Users\USER\Desktop\autop\AutoPrompt\estimator\__init__.py:31 in give_estimator                │
│                                                                                                  │
│   28                                                                                             │
│   29 def give_estimator(opt):                                                                    │
│   30 │   if opt.method == 'argilla':                                                             │
│    59 │   │   self.batch_id = 0                                                                  │
│    60 │   │   self.patient = 0                                                                   │
│                                                                                                  │
│ c:\Users\USER\Desktop\autop\AutoPrompt\estimator\__init__.py:31 in give_estimator                │
│                                                                                                  │
│   28                                                                                             │
│    59 │   │   self.batch_id = 0                                                                  │
│    60 │   │   self.patient = 0                                                                   │
│                                                                                                  │
│    60 │   │   self.patient = 0                                                                   │
│                                                                                                  │
│ c:\Users\USER\Desktop\autop\AutoPrompt\estimator\__init__.py:31 in give_estimator                │
│                                                                                                  │
│   28                                                                                             │
│   29 def give_estimator(opt):                                                                    │
│   30 │   if opt.method == 'argilla':                                                             │
│ ❱ 31 │   │   return ArgillaEstimator(opt.config)                                                 │
│ ❱ 31 │   │   return ArgillaEstimator(opt.config)                                                 │
│   32 │   elif opt.method == 'llm':                                                               │
│   33 │   │   return LLMEstimator(opt.config)                                                     │
│   34 │   elif opt.method == 'llm_batch':                                                         │
│                                                                                                  │
│ c:\Users\USER\Desktop\autop\AutoPrompt\estimator\estimator_argilla.py:29 in __init__             │
│                                                                                                  │
│    26 │   │   │   )                                                                              │
│    27 │   │   │   self.time_interval = opt.time_interval                                         │
│    28 │   │   except:                                                                            │
│ ❱  29 │   │   │   raise Exception("Failed to connect to argilla, check connection details")      │
│    30 │                                                                                          │
│    31 │   @staticmethod                                                                          │
│    32 │   def initialize_dataset(dataset_name: str, label_schema: set[str]):                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
Exception: Failed to connect to argilla, check connection details

**Comment by Eladlev** [comment]
Did you follow the instructions in the readme? Observe that this repo isn't compatible with Argilla V2, and you should downgrade to V1 (according to the instructions)
