### ISSUE TITLE
KeyError: 'samples'

### ISSUE THREAD

**Issue by alibabadoufu** [Eladlev/AutoPrompt#43]
Output of the sample_batches **doesn't have the sample keys**

```
        samples_list = [
            element for sublist in samples_batches for element in sublist["samples"]
        ]
```

Reference:
https://github.com/Eladlev/AutoPrompt/blob/c640cc0108e78601b474b380462a1a6274318fcc/optimization_pipeline.py#L192C25-L192C32

**Comment by Eladlev** [comment]
Could you provide the exact configuration?
In which mode did you try to run the code?

**Comment by alibabadoufu** [comment]
> Could you provide the exact configuration? In which mode did you try to run the code?

Hi, I am using huggingfacepipeline. 

Referring to the screenshot below, the all_results doesn't contain the key "samples"

![image](https://github.com/Eladlev/AutoPrompt/assets/47876361/b55c414e-aa65-4838-ba61-c14529984630)
