### ISSUE TITLE
The message "none is not an allowed value" suggests that "none" is not an acceptable option or setting within the configuration for Azure's ChatGPT.

### ISSUE THREAD

**Issue by nathin001** [Eladlev/AutoPrompt#44]
ValidationError: 1 validation error for LLMChain
llm
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by Eladlev** [comment]
Hi, I don't have currently access to Azure, 
I opened a PR for a fix that should solve the issue.
The only change in the config should be in all llm fields, modifying to:

```
  type: 'Azure'
  name: <deployment_name>
```

Please let me know if it solved the issue
