### ISSUE TITLE
KeyError: 'function_call'

### ISSUE THREAD

**Issue by cainiaogoroad** [Eladlev/AutoPrompt#73]
![image](https://github.com/user-attachments/assets/06a38fe0-bbf1-4ba1-9ece-1e4b0ca1fdad)
after run the command:python run_pipeline.py     --prompt "Does this movie review contain a spoiler? answer Yes or No"     --task_description "Assistant is an expert classifier that will classify a movie review, and let the user know if it contains a spoiler for the reviewed movie or not."     --num_steps 30.
it result in a promblem called "KeyError: 'function_call'" expressed in the above picture.
I would appreciate it if you would help me.

**Comment by Eladlev** [comment]
Hi, 
It seems that the model doesn't respond with the expected [structure](https://github.com/langchain-ai/langchain/issues/10397#issuecomment-1712470492)

Did you use the default config parameters? The most important thing is that the [meta-prompt LLM](https://github.com/Eladlev/AutoPrompt/blob/42555240b37d7be7646da5274fae57fd30ad9a70/config/config_default.yml#L50) should be a strong model and not GPT-3.5 for example, if you modify the model this might explain the error

**Comment by cainiaogoroad** [comment]
yes,i modify the gpt-4-1106-preview to gpt-3.5-turbo.
thank you！
