### ISSUE TITLE
Previous prompt score is nan

### ISSUE THREAD

**Issue by Chain-Mao** [Eladlev/AutoPrompt#78]
My previous prompt score is nan, i want to know what is the problem?
The output is that:
Starting step 6
Processing samples: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:45<00:00,  1.53s/it] 
Processing samples: 0it [00:00, ?it/s]
Previous prompt score:
nan

**Comment by Eladlev** [comment]
Can you provide the exact configuration?
1. All the config files modification
2. The running command

**Comment by Chain-Mao** [comment]
> Can you provide the exact configuration?
> 
> 1. All the config files modification
> 2. The running command

Sorry，I have solved this problem. I think it’s caused by the incorrect prompt translation from English to Chinese.
