### ISSUE TITLE
run_generation_pipeline is not working

### ISSUE THREAD

**Issue by oanastrut** [Eladlev/AutoPrompt#97]
Hi. When I try to run the generating movie reviews example using run_generation_pipeline.py I receive this error:

ValueError: At least one label specified must be in y_true

The config_generator.yml is looking like this:

            annotator:
                method : ''
            
            dataset:
                max_samples: 20
                label_schema:  ["1","2","3","4","5"]
            
            predictor:
                method : 'llm'
                config:
                    prompt: 'prompts/predictor_completion/prediction_generation.prompt'
                    mini_batch_size: 1
                    llm:
                        type: 'Azure'
                        name: 'my_engine_name'
                    num_workers: 7
            
            meta_prompts:
                folder: 'prompts/meta_prompts_generation'
                warmup: 1
            
            eval:
                function_name: 'ranking'
                error_threshold: 4

How can I fix this issue?

**Comment by Eladlev** [comment]
Hi,
This part of the configuration:
```
annotator:
   method : ''
```
This means that you are not using any annotators. It will work only if you are working with a custom dataset, and load it properly to the system with valid annotations. See here:
https://github.com/Eladlev/AutoPrompt/issues/51#issuecomment-2022592389

If you want to use either LLM annotator or a human annotator, you should modify this field according to the instructions.

**Comment by oanastrut** [comment]
Does this apply to the generation task as well? In the examples.md is mentioned that the annotator section in the generation config yaml file remains empty.
